import http from'node:http';import{readFile,writeFile,stat}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),pub=path.join(root,'public'),run=path.join(root,'data/runtime.json'),def=path.join(root,'data/default.json'),port=Number(process.env.PORT||4173),mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'};let db=JSON.parse(await readFile(def,'utf8'));try{db=JSON.parse(await readFile(run,'utf8'))}catch{}let state={ear:.31,score:92,blinkRate:14,headTilt:3.2,yawns:1,updatedAt:new Date().toISOString()},tick=0;const clients=new Set(),save=()=>writeFile(run,JSON.stringify(db,null,2)).catch(()=>{}),send=(res,n,x)=>{res.writeHead(n,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(x))};
async function body(req){return new Promise((ok,no)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e5)no(Error('Слишком большой запрос'))});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch{no(Error('Некорректный JSON'))}});req.on('error',no)})}function target(raw){try{const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))return null;if(process.env.RENDER&&u.protocol!=='https:')return null;return u}catch{return null}}
async function api(req,res,u){
 if(u.pathname==='/api/health'&&req.method==='GET')return send(res,200,{ok:true,service:'driveguard-fullstack',version:'1.0.0',uptime:Math.round(process.uptime())});
 if(u.pathname==='/api/state'&&req.method==='GET')return send(res,200,{ok:true,state,config:db.config,incidentCount:db.incidents.length});
 if(u.pathname==='/api/config'&&req.method==='GET')return send(res,200,{ok:true,config:db.config});
 if(u.pathname==='/api/config'&&req.method==='PUT'){const b=await body(req);for(const k of['deviceUrl','streamUrl','earThreshold','alarmDelayMs','autoSync'])if(k in b)db.config[k]=b[k];await save();return send(res,200,{ok:true,config:db.config})}
 if(u.pathname==='/api/incidents'&&req.method==='GET')return send(res,200,{ok:true,incidents:db.incidents});
 if(u.pathname==='/api/incidents'&&req.method==='POST'){const b=await body(req),row={id:crypto.randomUUID(),time:new Date().toLocaleTimeString('ru-RU'),kind:String(b.kind||'Событие').slice(0,50),duration:Number(b.duration||0),level:b.level==='critical'?'critical':'warning'};db.incidents.unshift(row);db.incidents=db.incidents.slice(0,100);await save();return send(res,201,{ok:true,incident:row})}
 if(u.pathname==='/api/incidents'&&req.method==='DELETE'){db.incidents=[];await save();return send(res,200,{ok:true})}
 if(u.pathname==='/api/incidents.csv'){const lines=['time,event,duration_seconds,severity',...db.incidents.map(x=>[x.time,x.kind,x.duration,x.level].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))];res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="driveguard-incidents.csv"'});return res.end('\ufeff'+lines.join('\n'))}
 if(u.pathname==='/api/command'&&req.method==='POST'){const b=await body(req),to=target(String(b.target||''));if(!to)return send(res,400,{ok:false,error:process.env.RENDER?'На Render нужен HTTPS-адрес локального моста':'Некорректный адрес'});try{const r=await fetch(to,{signal:AbortSignal.timeout(3500)}),text=await r.text();return send(res,r.ok?200:502,{ok:r.ok,status:r.status,response:text.slice(0,800)})}catch{return send(res,502,{ok:false,error:'Устройство или мост недоступны'})}}
 if(u.pathname==='/api/events'){res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'});res.write(`event: telemetry\ndata: ${JSON.stringify(state)}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res));return}
 return send(res,404,{ok:false,error:'Маршрут не найден'})}
async function files(res,u){let rel=decodeURIComponent(u.pathname);if(rel==='/'||!path.extname(rel))rel='/index.html';const f=path.normalize(path.join(pub,rel));if(!f.startsWith(pub))return send(res,403,{ok:false});try{await stat(f);res.writeHead(200,{'content-type':mime[path.extname(f)]||'application/octet-stream','cache-control':path.extname(f)==='.html'?'no-cache':'public, max-age=3600'});res.end(await readFile(f))}catch{res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(await readFile(path.join(pub,'index.html')))}}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url||'/','http://localhost');try{u.pathname.startsWith('/api/')?await api(req,res,u):await files(res,u)}catch(e){if(!res.headersSent)send(res,500,{ok:false,error:e.message||'Ошибка сервера'})}});server.listen(port,'0.0.0.0',()=>console.log(`driveguard-fullstack listening on ${port}`));setInterval(()=>{tick++;const low=tick%31<2,e=low?.17+Math.random()*.018:.285+Math.random()*.045,s=Math.max(15,Math.min(98,Math.round((e-.14)*520)));state={ear:+e.toFixed(3),score:s,blinkRate:13+Math.round(Math.random()*3),headTilt:+(2+Math.random()*2.5).toFixed(1),yawns:1,updatedAt:new Date().toISOString()};const m=`event: telemetry\ndata: ${JSON.stringify(state)}\n\n`;for(const c of clients)c.write(m)},1000);const stop=()=>server.close(()=>process.exit(0));process.on('SIGTERM',stop);process.on('SIGINT',stop);
